os:
  - linux
  - osx
language: generic
sudo: required
osx_image: xcode10.3
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" ; fi
script:
  - swift build
  - swift test