os:
  - linux
  - osx
language: generic
sudo: required
osx_image: xcode10.3
env:
  - SWIFT_VERSION=5.0.3
  - SWIFT_VERSION=5.1-DEVELOPMENT-SNAPSHOT-2019-09-05-a
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
  - swift test